# Generated by Django 5.2.1 on 2025-05-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2025)),
                ('description', models.TextField()),
                ('tech_stack', models.TextField()),
                ('programmer', models.CharField()),
                ('image', models.ImageField(default='default_image.png', upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
